### ISSUE TITLE
Missing server for e4k

### ISSUE THREAD

**Issue by TytanGamesYt** [danadum/e4k-rankings#1]
e4k-live-preclient-pl1-game.goodgamestudios.com
Is any way to add it?

**Comment by danadum** [comment]
do you know by any chance the key used to send the messages on this server ? it's something looking like EmpirefourkingdomsExGG_X, without it i can't do much sadly.

**Comment by TytanGamesYt** [comment]
I'll try to find that key if that's possible by some network analyse tools or by another way... After all, I'm also a programmer so maybe I can do something to gain it

**Comment by TytanGamesYt** [comment]
And I found it ^^
EmpirefourkingdomsExGG2_3

**Comment by danadum** [comment]
Yep that's the one i needed thanks, so it has been added to the list of server (as closed beta 1).
For the monthly event sadly it's not possible, ggs servers don't give those datas.

**Comment by TytanGamesYt** [comment]
Sure thanks. If you'll want some help or something then I can help you too because I like programming and helping peoples ^^
